version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: dschang-signal-db
    environment:
      POSTGRES_DB: dschang-signal
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"