spring:
  application:
    name: dschang-signal
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://localhost:5432/dschang-signal
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  base-path: /api
jwt:
  secret: dschang-signal-secret-key-must-be-at-least-32-chars
  expiration: 86400000