spring:
  application:
    name: dschang-signal
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://localhost:5432/dschang-signal
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  base-path: /api
jwt:
  secret: dschang-signal-secret-key-must-be-at-least-32-chars
  expiration: 86400000