spring:
  application:
    name: dschang-signal
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://localhost:5432/dschangsignal
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  base-path: /api

jwt:
  secret: "DschangSignalSecureKey2026AdvancedEncryptionStandardKey"
  expiration: 86400000